### PR TITLE
Fix items with many combinations in order 132

### LINKED ISSUE #132: Fix items in order with many times the same product but with different combinations
# Abstract

Currently the order will register two items if an item has many attributes in a combination, and only one if an item was ordered many times with different combinations

# Details

N/A

# Requester

@PaulGirardin

### PR DESCRIPTION
**Pull request by PaulGirardin**
-----
fixes #132 (automatic)

### CODE REVIEW

File: classes/SRBItem.php [hunk 1]
```diff
@@ -13,10 +13,13 @@ public function __construct($psProduct)
...
         $this->label = $this->product->label;
         $this->reference = $this->product->getReference();
+        $combinations = $this->product->getPreciseCombinationInOrder($psProduct['id_order'], $psProduct['id_product_attribute']);
 
-        if ($psProduct['attribute_name']) {
-            $this->label .= ' - ' . $psProduct['attribute_name'];
-            $this->barcode = $psProduct['attribute_ean13'];
+        if ($combinations) {
+            foreach ($combinations as $key => $combination) {
+                $this->label .= ' - ' . $combination['attribute_name'];
```
Comment (leo-martin) [inline classes/SRBItem.php]: good

**Comment by leo-martin** [comment]
1.0.15
